{
  "dataset_path": "./result/all_pca_patient_variables_singlegait.csv",
  "name": "sweep_regression",
  "method": "grid",
  "metric":{
    "name": "test_accuracy",
    "goal": "minimize",
  },

  "parameters": {
    "input_activity":
      {
        "distribution": "categorical",
        "values": ["Gait", "Stair Ascent", "Stair Descent", "Sit to Stand"]
      },
    "output_activity":
      {
        "distribution": "categorical",
        "values": ["Gait", "Stair Ascent", "Stair Descent", "Sit to Stand"]
      },
    "selected_model":
      {
        "distribution": "categorical",
        "values": ["svm", "decision_tree", "Neighbors", "logregression"]
      },
    "feature_reduction":
      {
        "distribution": "categorical",
        "values": [true, false]
      },
    "scale":
      {
        "distribution": "categorical",
        "values": [true, false]
      },
    "model_name":
      {
        "distribution": "categorical",
        "values": ["svm", "decision_tree", "Neighbors", "logregression"]
      },
    "bilstm_hidden_size":
      {
        "distribution": "categorical",
        "values": [32]
      },
    "bilstm_num_layers":
      {
        "distribution": "categorical",
        "values": [1]
      },
    "bilstm_dropout_p":
      {
        "distribution": "categorical",
        "values": [0.2]
      },
    "optimizer_name":
      {
        "distribution": "categorical",
        "values": ["Adam"]
      },
    "learning_rate":
      {
        "distribution": "categorical",
        "values": [0.001]
      },
    "n_epoch":
      {
        "distribution": "categorical",
        "values": [5]
      },
    "batch_size":
      {
        "distribution": "categorical",
        "values": [50]
      },
    "loss":
      {
        "distribution": "categorical",
        "values": ["MSE"]
      },
    "loss_weight":
      {
        "distribution": "categorical",
        "values": [[1 , 1, 1]]
      },
    "nfold":
      {
        "distribution": "categorical",
        "values": [17]
      },
    "cv_fold_type":
      {
        "distribution": "categorical",
        "values": ["inter", "intra"]
      },
  }
}